version: "3.4"
services:
  wpdb:
    image: mysql:5.7
    volumes:
    - ./data/db:/var/lib/mysql
    - ./data/dump:/docker-entrypoint-initdb.d
    restart: always
    ports:
    - "2021:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  wp:
    image: wordpress:latest
    restart: always
    volumes:
    - ./html:/var/www/html
    ports:
    - "2020:80"
    links:
    - wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
    - 2121:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: wpdb
    links:
    - wpdb:mysql